/** Disposable PGlite fixture/wrapper/seed checks. No remote tools or real Auth. */
import {PGlite} from '@electric-sql/pglite';import {readFile} from 'node:fs/promises';import {randomUUID,randomBytes,createHash} from 'node:crypto';import assert from 'node:assert/strict';
const db=new PGlite(),root=new URL('../../',import.meta.url),read=p=>readFile(new URL(p,root),'utf8');let stage='setup',count=0;
const test=async(n,f)=>{stage=n;await f();console.log('PASS '+(++count)+' '+n);};const row=async(s,p)=>(await db.query(s,p)).rows[0];const one=async(s,p)=>Object.values(await row(s,p))[0];const hash=s=>createHash('sha256').update(s).digest('hex');
const ids={member:'15cbc7a4-92f6-48d8-abb2-ed68f7612271',a:'1e7259c2-ad13-43a1-b34b-cba71533e844',b:'ed2433cb-bc6e-4b23-aa57-000839292ec4',outsider:randomUUID()};const sessions={},factors={};let start;const files='docs/day07/activation/';const fs=JSON.parse(await read(files+'FIXTURE_BINDINGS.json'));const primary=fs[0];const token='VNE2:'+'A'.repeat(43);
const run=async(file,{approval=true,rehearsal=false}={})=>{let sql=await read(files+file);const settings=(approval?"select set_config('vne.day07.approval_ref','OFFLINE_TEST_ONLY',true);":'')+(start?"select set_config('vne.day07.approved_start_utc','"+start+"',true);":'')+(rehearsal?"select set_config('vne.day07.rehearsal_evidence_ref','OFFLINE_REHEARSAL_ONLY',true);":'');sql=sql.replace('begin;','begin;'+settings);try{return await db.exec(sql);}catch(e){await db.exec('rollback');throw e;}};
const denied=async(fn,reason)=>assert.rejects(fn,e=>e.code===reason||String(e.message).includes(reason));
const call=async(who,c)=>db.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.query("select set_config('request.jwt.claims',$1,true)",[JSON.stringify({sub:ids[who],session_id:sessions[who],aal:who==='member'||who==='outsider'?'aal1':'aal2',is_anonymous:false,role:'authenticated'})]);return(await tx.query('select public.vne_qr_command($1::jsonb) result',[JSON.stringify(c)])).rows[0].result;});
async function negative(update,params,expected,restore,restoreParams=params){await db.query(update,params);try{await denied(()=>run('30_CONFIG_ENABLE_PROPOSAL.sql'),expected);assert.equal(await one('select enabled from private.qr_admission_config'),false);}finally{await db.query(restore,restoreParams);}}
try{
 await db.exec((await read('tests/db/supabase-stub.sql')).replace('create extension if not exists pgcrypto with schema extensions;',''));
 await db.exec("alter table auth.users add column email_confirmed_at timestamptz default now(),add column is_anonymous boolean default false,add column banned_until timestamptz,add column raw_user_meta_data jsonb default '{}',add column raw_app_meta_data jsonb default '{}';alter table auth.sessions add column aal text,add column factor_id uuid;create table auth.mfa_factors(id uuid primary key,user_id uuid,factor_type text default 'totp',status text default 'verified');create function extensions.digest(data text,algorithm text) returns bytea language sql immutable as $$select sha256(convert_to(data,'UTF8'))$$;create table extensions.offline_entropy(id int,payload bytea);create function extensions.gen_random_bytes(n integer) returns bytea language plpgsql volatile as $$declare b bytea;begin if n<>32 then raise exception 'offline32only';end if;delete from extensions.offline_entropy where id=(select min(id) from extensions.offline_entropy) returning payload into b;return b;end$$;");
 for(let i=0;i<10;i++)await db.query('insert into extensions.offline_entropy values($1,$2)',[i,randomBytes(32)]);
 for(const v of ['20261006170437-statements','20261006170540-statements'])await db.exec('begin;'+await read('docs/day07/recovery/'+v+'.sql')+'commit;');for(const v of ['20261007153318','20261007171324'])await db.exec(await read('docs/day07/recovery/'+v+'.sql'));
 await db.exec(await read('docs/day07/recovery/demo-qr-actor-20261008.sql'));assert.equal(await one("select encode(sha256(convert_to(prosrc,'UTF8')),'hex') from pg_proc where oid='private.qr_require_actor()'::regprocedure"),'237191982ee2deb9a1e102dd11b4d9e33eabf596d1fdf83ef380513d12acd776');
 for(const[who,id]of Object.entries(ids)){sessions[who]=randomUUID();factors[who]=randomUUID();await db.query('insert into auth.users(id,email) values($1,$2)',[id,who+'@offline.invalid']);await db.query('insert into auth.mfa_factors(id,user_id) values($1,$2)',[factors[who],id]);await db.query("insert into auth.sessions(id,user_id,aal,factor_id,not_after) values($1,$2,$3,$4,clock_timestamp()+interval '1 day')",[sessions[who],id,['a','b'].includes(who)?'aal2':'aal1',factors[who]]);}
 start=new Date(Date.now()+60000).toISOString();
 await test('missing approval or missing scanner MFA causes no fixture writes',async()=>{await denied(()=>run('10_FIXTURE_ADMISSION_ROLES_PROPOSAL.sql',{approval:false}),'explicit_future_start');await db.query("update auth.mfa_factors set status='unverified' where id=$1",[factors.b]);await denied(()=>run('10_FIXTURE_ADMISSION_ROLES_PROPOSAL.sql'),'two_live_MFA');await db.query("update auth.mfa_factors set status='verified' where id=$1",[factors.b]);assert.equal(await one('select count(*)::int from public.events'),0);});
 await test('missed timestamp is rejected and never moved automatically',async()=>{const future=start;start=new Date(Date.now()-1000).toISOString();await denied(()=>run('10_FIXTURE_ADMISSION_ROLES_PROPOSAL.sql'),'missed_start');start=future;});
 await test('four exact synthetic fixtures, eight event roles, three admissions and held-only outbox',async()=>{await run('10_FIXTURE_ADMISSION_ROLES_PROPOSAL.sql');assert.equal(await one('select count(*)::int from public.events'),4);assert.equal(await one('select count(*)::int from public.staff_assignments'),8);assert.equal(await one("select count(*)::int from private.member_admission where state='admitted'"),3);assert.equal(await one("select count(*)::int from private.outbox where status='held'"),4);assert.equal(await one('select count(*)::int from public.payments'),0);});
 await test('closed wrapper is exact and cannot execute before explicit grant',async()=>{await run('20_SCOPED_WRAPPER_CLOSED_PROPOSAL.sql');assert.equal(await one("select encode(sha256(convert_to(prosrc,'UTF8')),'hex') from pg_proc where oid='public.vne_qr_command(jsonb)'::regprocedure"),(await read(files+'WRAPPER_BODY_SHA256.txt')).trim());await denied(()=>call('member',{action:'list'}),'42501');});
 await test('grant is authenticated-only and private helper remains inaccessible',async()=>{await run('21_WRAPPER_GRANT_PROPOSAL.sql');assert.equal(await one("select has_function_privilege('authenticated','public.vne_qr_command(jsonb)','execute')"),true);for(const r of ['anon','service_role'])assert.equal(await one("select has_function_privilege($1,'public.vne_qr_command(jsonb)','execute')",[r]),false);assert.equal(await one("select has_function_privilege('authenticated','private.qr_command(jsonb)','execute')"),false);});
 await test('amount/currency/null review reason drift blocks activation',async()=>{for(const[col,bad,good]of [['amount_minor',999999,1000],['currency','USD','RUB'],['review_reason',null,'Synthetic state fixture only; no payment provider called.']])await negative(`update public.orders set ${col}=$1 where id=$2`,[bad,primary.order],'exact_paid_sandbox',`update public.orders set ${col}=$1 where id=$2`,[good,primary.order]);});
 await test('reservation expiry and scanner window drift block activation',async()=>{await negative("update public.reservations set expires_at=expires_at+interval '1 second' where id=$1",[primary.reservation],'exact_reservation',"update public.reservations set expires_at=expires_at-interval '1 second' where id=$1");await negative("update public.staff_assignments set valid_until=valid_until-interval '1 minute' where id=$1",[primary.scannerA],'exact_event_scanner',"update public.staff_assignments set valid_until=valid_until+interval '1 minute' where id=$1");});
 await test('source audit or held notification drift blocks activation',async()=>{const audit=await row("select id,details from private.audit_log where action='day07.synthetic_fixture' and object_id=$1",[primary.event]);await negative("update private.audit_log set details=details-'approvalRef' where id=$1",[audit.id],'exact_source_audit','update private.audit_log set details=$1 where id=$2',[JSON.stringify(audit.details),audit.id]);const box=await row("select id from private.outbox where payload->>'eventId'=$1",[primary.event]);await negative("update private.outbox set status='pending' where id=$1",[box.id],'exact_held_notification',"update private.outbox set status='held' where id=$1");});
 await test('exact ready fixture can activate; wrapper still refuses before window',async()=>{await run('30_CONFIG_ENABLE_PROPOSAL.sql');assert.equal(await one('select enabled from private.qr_admission_config'),true);await denied(()=>call('member',{action:'list'}),'outside_approved_window');});
 // Offline time travel ONLY: shift all correlated fixture timestamps together, preserving their offsets.
 // This is not a remote proposal and does not authorize altering an approved real run window.
 await db.exec("update public.events set starts_at=starts_at-interval '2 minutes',qr_release_at=qr_release_at-interval '2 minutes',address_reveal_at=address_reveal_at-interval '2 minutes',entry_opens_at=entry_opens_at-interval '2 minutes',entry_closes_at=entry_closes_at-interval '2 minutes';update public.reservations set expires_at=expires_at-interval '2 minutes';update public.staff_assignments set valid_from=valid_from-interval '2 minutes',valid_until=valid_until-interval '2 minutes';update private.audit_log set details=jsonb_set(jsonb_set(details,'{windowStart}',to_jsonb((details->>'windowStart')::timestamptz-interval '2 minutes')),'{windowEnd}',to_jsonb((details->>'windowEnd')::timestamptz-interval '2 minutes')) where action in('day07.synthetic_fixture','day07.synthetic_enable');");
 await test('wrapper limits lists/catalogs and rejects outsider/extra scope',async()=>{assert.equal((await call('member',{action:'list'})).items.length,4);assert.equal((await call('a',{action:'catalog'})).events.length,4);await denied(()=>call('outsider',{action:'list'}),'42501');await denied(()=>call('member',{action:'status',eventId:primary.event,participationId:fs[1].participation}),'42501');await denied(()=>call('a',{action:'verify',eventId:randomUUID(),token:'malformed'}),'42501');});
 await test('seed demands exact rehearsal marker and preserves held notifications',async()=>{await denied(()=>run('40_PUBLIC_CONCURRENCY_SEED_PROPOSAL.sql'),'exact_seed_and_rehearsal');await run('40_PUBLIC_CONCURRENCY_SEED_PROPOSAL.sql',{rehearsal:true});assert.equal(await one('select count(*)::int from private.ticket_passes'),1);assert.equal(await one('select count(*)::int from private.outbox'),4);assert.equal(await one("select details->>'actualOwnerIssue' from private.audit_log where action='day07.synthetic_race_pass_seed'"),'false');});
 await test('seed retry cannot overwrite existing pass',async()=>await denied(()=>run('40_PUBLIC_CONCURRENCY_SEED_PROPOSAL.sql',{rehearsal:true}),'fresh_fixture_required'));
 let win,operation=randomUUID();
 await test('public concurrency fixture verifies; sequential accepted/used and replay retain one primary',async()=>{assert.equal((await call('a',{action:'verify',eventId:primary.event,token})).receipt.outcome,'ready');const c={action:'checkin',eventId:primary.event,token,operationId:operation,expectedVersion:1};win=await call('a',c);assert.equal(win.receipt.outcome,'simulated_accepted');assert.equal((await call('b',{...c,operationId:randomUUID()})).receipt.outcome,'used');const replay=await call('a',c);assert.deepEqual(replay.receipt,win.receipt);assert.equal(replay.replayed,true);assert.equal(await one('select count(*)::int from private.ticket_checkins where participation_id=$1',[primary.participation]),1);});
 await test('cached winner replay still requires current MFA, staff and non-demo identity',async()=>{
  const command={action:'checkin',eventId:primary.event,token,operationId:operation,expectedVersion:1};
  const before=await one('select count(*)::int from private.qr_command_receipts');
  await db.query("update auth.sessions set aal='aal1' where id=$1",[sessions.a]);
  try{await denied(()=>call('a',command),'42501');}finally{await db.query("update auth.sessions set aal='aal2' where id=$1",[sessions.a]);}
  await db.query("update public.staff_assignments set revoked_at=clock_timestamp() where id=$1",[primary.scannerA]);
  try{await denied(()=>call('a',command),'42501');}finally{await db.query("update public.staff_assignments set revoked_at=null where id=$1",[primary.scannerA]);}
  await db.query("update auth.users set raw_app_meta_data=jsonb_build_object('demo_only',true) where id=$1",[ids.a]);
  try{await denied(()=>call('a',command),'42501');}finally{await db.query("update auth.users set raw_app_meta_data='{}' where id=$1",[ids.a]);}
  await denied(()=>call('outsider',command),'42501');
  await denied(()=>call('a',{...command,expectedVersion:2}),'idempotency_conflict');
  assert.equal(await one('select count(*)::int from private.qr_command_receipts'),before);
 });
 await test('expired database window blocks even an existing cached winner receipt without mutation',async()=>{
  const command={action:'checkin',eventId:primary.event,token,operationId:operation,expectedVersion:1};
  const before=await one('select count(*)::int from private.qr_command_receipts');
  const retime=sign=>db.query(`update public.events set starts_at=starts_at${sign}interval '21 minutes',qr_release_at=qr_release_at${sign}interval '21 minutes',address_reveal_at=address_reveal_at${sign}interval '21 minutes',entry_opens_at=entry_opens_at${sign}interval '21 minutes',entry_closes_at=entry_closes_at${sign}interval '21 minutes' where id=$1`,[primary.event]);
  await retime('-');try{await denied(()=>call('a',command),'outside_approved_window');}finally{await retime('+');}
  assert.equal(await one('select count(*)::int from private.qr_command_receipts'),before);
  assert.equal(await one('select count(*)::int from private.ticket_checkins'),1);
  const again=await call('a',command);assert.deepEqual(again.receipt,win.receipt);assert.equal(again.replayed,true);
 });
 await test('receipt post-fence rolls back mutated inner effects on foreign participation, including negative outcomes',async()=>{
  const original=JSON.parse(await read('docs/day07/recovery/live-qr-functions.json')).find(x=>x.proname==='qr_command').definition;
  try{for(const outcome of ['simulated_accepted','used','too_early','version_conflict']){await db.exec(`create or replace function private.qr_command(_command jsonb) returns jsonb language plpgsql security definer set search_path='' as $$begin insert into private.audit_log(action,object_type,result) values('OFFLINE_SCOPE_ROLLBACK','test','ok');return jsonb_build_object('receipt',jsonb_build_object('eventId',_command->>'eventId','participationId','${randomUUID()}','outcome','${outcome}'));end$$;`);await denied(()=>call('a',{action:'checkin',eventId:primary.event,token,operationId:randomUUID(),expectedVersion:2}),'fixture_binding_conflict');assert.equal(await one("select count(*)::int from private.audit_log where action='OFFLINE_SCOPE_ROLLBACK'"),0);}}finally{await db.exec(original);}
 });
 await test('emergency close immediately revokes authenticated RPC and disables config',async()=>{await run('90_EMERGENCY_DISABLE_PROPOSAL.sql');assert.equal(await one('select enabled from private.qr_admission_config'),false);await denied(()=>call('a',{action:'catalog'}),'42501');});
 await test('cleanup rejects changed role binding before modifying unrelated assignments',async()=>{await db.query('update public.staff_assignments set user_id=$1 where id=$2',[ids.outsider,primary.scannerA]);try{await denied(()=>run('91_SCOPED_CLEANUP_PROPOSAL.sql'),'assignment_binding_drift');}finally{await db.query('update public.staff_assignments set user_id=$1 where id=$2',[ids.a,primary.scannerA]);}});
 await test('cleanup archives four events, revokes8 roles/3admissions, preserves primary/pass/receipts',async()=>{const before=await one('select count(*)::int from private.qr_command_receipts');await run('91_SCOPED_CLEANUP_PROPOSAL.sql');assert.equal(await one("select count(*)::int from public.events where status='archived'"),4);assert.equal(await one('select count(*)::int from public.staff_assignments where revoked_at is not null'),8);assert.equal(await one("select count(*)::int from private.member_admission where state='revoked'"),3);assert.equal(await one('select count(*)::int from private.ticket_checkins'),1);assert.equal(await one('select count(*)::int from private.ticket_passes'),1);assert.equal(await one('select count(*)::int from private.qr_command_receipts'),before);assert.equal(await one('select count(*)::int from public.payments'),0);});
 console.log(JSON.stringify({status:'PASS',groups:count,environment:'ONE_PGLITE_CONNECTION',genuineAuth:'NOT_VERIFIED',concurrency:'NOT_VERIFIED',remoteActions:0}));
}catch(e){console.error(JSON.stringify({status:'FAIL',stage,code:e.code??e.name,message:String(e.message).replace(/VNE[12]:[A-Za-z0-9_-]+/g,'[REDACTED]').slice(0,220)}));process.exitCode=1;}finally{await db.close();}
