import { brandColorTokens } from "../src/config/design-config";

export const BRAND_TOKENS_PATH = "src/styles/brand-tokens.css";

/** Single source of the generated CSS, shared by the generate and check scripts. */
export function renderBrandTokensCss() {
  return [
    "/* Generated by scripts/generate-brand-tokens.ts. Do not edit by hand. */",
    ":root {",
    ...Object.entries(brandColorTokens).map(
      ([name, color]) => `  --${color.cssName ?? name}: ${color.oklch};`,
    ),
    "}",
    "",
  ].join("\n");
}
