import {build} from 'esbuild';
import {strict as assert} from 'node:assert';
import path from 'node:path';
const output=await build({entryPoints:['scripts/auth/public-pass.ts'],bundle:true,write:false,format:'esm',platform:'node',alias:{'@':path.resolve('src')}});
const {default:withPublicPass}=await import('data:text/javascript;base64,'+Buffer.from(output.outputFiles[0].text).toString('base64'));
const worker=withPublicPass({fetch:async()=>new Response('protected',{status:401})},{fetch:async()=>new Response('public pass shell')});
const env={VNE_PASS_SERVICE_URL:'https://issuer.synthetic.invalid',VNE_PASS_ADMIN_KEY:'a'.repeat(40),VNE_TICKETS_PUBLIC_PASS:'1'};
const send=(route,method='GET',body,extra={},e=env)=>worker.fetch(new Request('https://site.synthetic.invalid'+route,{method,headers:{Origin:'https://site.synthetic.invalid','Content-Type':'application/json',...extra},...(body?{body}: {})}),e,{});
let calls=0;globalThis.fetch=async(url,options)=>{calls++;assert.equal(url,env.VNE_PASS_SERVICE_URL+'/api/pass/read');assert.equal(options.headers.Authorization,undefined);return Response.json({pass:{id:'sample',access:'GENERAL',status:'active',event:{id:'e',title:'Synthetic'},name:'Test',qrText:'VNE1:'+'s'.repeat(43)}})};
assert.equal(await(await send('/pass')).text(),'public pass shell');
for(const url of ['/admin','/admin/tickets','/scan','/pass/','/_serverFn/fake','/api/tickets/read/'])assert.equal((await send(url)).status,401);
assert.equal((await send('/pass','POST')).status,401);
assert.equal((await send('/pass','GET',null,{},{})).status,401);
assert.equal((await send('/api/tickets/read','POST',JSON.stringify({token:'t'.repeat(43)}),{},{})).status,503);
assert.equal((await send('/api/tickets/read','GET')).status,405);
assert.equal((await send('/api/tickets/read','POST',JSON.stringify({token:'t'.repeat(43)}),{Origin:'https://evil.invalid'})).status,403);
assert.equal((await send('/api/tickets/read','POST','x'.repeat(1025))).status,413);
assert.equal((await send('/api/tickets/read','POST',JSON.stringify({token:'bad'}))).status,400);
assert.equal(calls,0);
const read=await send('/api/tickets/read','POST',JSON.stringify({token:'t'.repeat(43)}));assert.equal(read.status,200);assert.equal(read.headers.get('referrer-policy'),'no-referrer');assert.equal((await read.json()).state,'ok');assert.equal(calls,1);
console.log(JSON.stringify({status:'PASS',publicRoutes:['GET|HEAD /pass','POST /api/tickets/read'],protectedRoutes:6,backend:'mock issuer; no live credentials'}));
